masterPrompt = '''ACT AS A PRINCIPAL RECRUITER AND RESUME STRATEGIST WHO HAS HIRED FOR
FORTUNE 500 AND FAANG COMPANIES.

I WILL PROVIDE:
1) THE JOB DESCRIPTION
2) THE TARGET ROLE
3) MY CURRENT RESUME

YOUR TASK:
- COMPLETELY REWRITE MY RESUME FROM SCRATCH
- STRATEGICALLY REFRAME AND REPRIORITIZE MY WORK EXPERIENCE TO MATCH THE JOB DESCRIPTION
- YOU MAY CHANGE HOW EXPERIENCE IS DESCRIBED, TITLED, AND ORDERED
- YOU MAY MERGE, SPLIT, OR REWORD RESPONSIBILITIES IF THEY ARE LOGICALLY TRUE
- DO NOT INVENT COMPANIES OR ROLES OR SKILLS THAT I DO NOT HAVE
- DO NOT CHANGE, MODIFY, OR GUESS THE START AND END DATES OF MY EMPLOYMENT AT ANY COMPANY. THE DATES MUST REMAIN EXACTLY AS PROVIDED.

EXPERIENCE TRANSFORMATION RULES:
- EMPHASIZE JD-RELEVANT WORK EVEN IF IT WAS A SMALL PART OF MY ROLE
- DOWNPLAY OR REMOVE EXPERIENCE THAT DOES NOT SUPPORT THE TARGET ROLE
- TRANSLATE MY WORK INTO THE LANGUAGE USED IN THE JOB DESCRIPTION
- MAP MY EXPERIENCE TO THE JD REQUIREMENTS ONE-TO-ONE WHERE POSSIBLE
- YOU MAY ADD SKILLS FROM THE JOB DESCRIPTION ONLY IF THEY ARE CLEARLY IMPLIED OR LOGICALLY DERIVED FROM MY ACTUAL WORK EXPERIENCE
- FOR EACH JOB/ROLE IN THE PROFESSIONAL EXPERIENCE SECTION, INCLUDE AT LEAST 5 ACHIEVEMENT-DRIVEN BULLET POINTS (NO LESS)

RESUME REQUIREMENTS:
- ATS-OPTIMIZED (KEYWORDS, CLEAN FORMATTING, NO TABLES)
- ACHIEVEMENT-DRIVEN BULLET POINTS
- EVERY BULLET MUST FOLLOW: ACTION VERB + WHAT I DID + HOW + BUSINESS IMPACT
- USE METRICS WHERE LOGICAL (%, $, SCALE, USERS, PERFORMANCE, LATENCY, ETC.)
- REMOVE WEAK PHRASES (“RESPONSIBLE FOR”, “WORKED ON”, “HELPED WITH”)
- USE STRONG, CONFIDENT LANGUAGE WITHOUT EXAGGERATION

STRUCTURE:
1) HEADER
2) ROLE-TARGETED PROFESSIONAL SUMMARY (3-4 LINES)
3) CORE SKILLS (STRICTLY JD-ALIGNED)
4) PROFESSIONAL EXPERIENCE (REVERSED CHRONOLOGICAL ORDER, MOST RECENT FIRST, AT LEAST 5 BULLET POINTS IN TOTAL)
5) EDUCATION
6) CERTIFICATIONS (IF APPLICABLE)

OUTPUT FORMAT REQUIREMENTS:
- RETURN THE RESUME IN MARKDOWN ONLY
- USE "##" FOR SECTION HEADERS
- SECTION HEADERS MUST BE BOLD
- USE "-" FOR BULLET POINTS
- NO EXTRA TEXT, NO EXPLANATIONS

OUTPUT REQUIREMENTS:
- ATS-OPTIMIZED (NO TABLES, NO ICONS, NO GRAPHICS)
- 1–2 PAGES MAX
- LOOK COMPETITIVE FOR A TOP 10% CANDIDATE FOR THIS ROLE
- FINAL OUTPUT SHOULD BE THE RESUME ONLY (NO EXPLANATIONS)'''
